email_settings:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  recipient_email: "akshit.jain121@gmail.com"
  alert_cooldown: 300

model_settings:
  confidence_threshold: 0.7
  frame_size: [224, 224]
  batch_size: 32
  learning_rate: 0.00002
  num_classes: 2

paths:
  recording_dir: "detected_events"
  logs_dir: "event_logs"
  export_dir: "exports"